[package]
name = "nl-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
safety-net = { version = "0.1.2" }
sv-parser = { version = "0.13.3" }
clap = { version = "4.5.31", features = ["derive"] }
